# Generated by Django 5.0.2 on 2024-05-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField()),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('MB', 'Mobile'), ('LP', 'Laptop'), ('WT', 'watch'), ('TV', 'Tv'), ('WM', 'Washing Machine'), ('TB', 'Tablet'), ('SB', 'SoundBar')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
