# Generated by Django 5.0.2 on 2024-06-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_payment_orderplaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holdername', models.CharField(max_length=50)),
                ('cardnumber', models.IntegerField()),
                ('expiry_data', models.DateField(verbose_name='')),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
