# Generated by Django 5.0.2 on 2024-06-19 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_payments_remove_payment_user_delete_orderplaced_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='expiry_data',
            new_name='expiry_date',
        ),
    ]
